---
- name: service management
  hosts: all
  tasks:
    - name: Enable and start httpd
      service:
        name: httpd
        enabled: yes
        state: started
    - name: Enable and start mariadb
      service:
        name: mariadb
        enabled: yes
        state: started

